default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: emtags_development

test:
  <<: *default
  database: emtags_test

production:
  <<: *default
  database: emtags_production
  # username: emtags
  # password: <%= ENV['EMTAGS_DATABASE_PASSWORD'] %>
